version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cet-db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: cet-db
      SPRING_DATASOURCE_PASSWORD: _SJKyjs159753

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: _SJKyjs159753
      MYSQL_DATABASE: cet-db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local
