spring:
  application:
    name: CET-GRADE-SYSTEM
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.120.50.123:3306/cet-db?useSSL=false&serverTimezone=UTC
    username: cet-db
    password: _SJKyjs159753
server:
  port: 80
mybatis:
  type-aliases-package: com.dre4m.cetgradesystem.domain